dist: bionic
language: bash
services:
- docker
before_install:
- bash cd docker && ./build.sh
deploy:
  provider: script
  script: bash docker/push.sh
  on:
    branch: master
env:
  global:
  - secure: Qa1rijfss8SAkGS/Ipl1SIShaMmVa0GKBeGfvKMFicJ1Smw5wfBQTK1yp/XTyFnDe/aNB8a5YoSGmR1BZu490i2BJ4MRIKzlT88is2xh5qD/f7kGQN0NA2OQOrxXO0efSm8i0rKrP72pTgxtpzBscOkk/ybWNLWW5Q/dp35l9RataOoi1m5OJ4aY67rMgm41HVx24Fq4FeRMiuzqJ73PUkHE1a2qSPkhbzUzmaDZbvvK6e/CuTCAi21KL3XMOwhPtrURHDxLsieavQqfTSIOmW+OGhkIMRIBbqaOUJu7xK0Yt9yijR6xTYbfediBHyLGAHg3Q5qsCEPIRgxNiNJw5Y5du0yOA0SOnZKAGS8vVAg62PtoHk0c4slM3eKye3W62mZWNUuBm4Mr7JOtuFLMSJdmzwkt4TPp22Y3SZka1Q5e+MqSQ/q8M7lpKUw61tfKm4sfahWZxCzVq16+5JcVJPIb6QQtJP2bboNQ0I3eCaSK+qJ0+YyEvUod7ZmzoNrMGUUlEpNxVfJcFtzoLe4oCyWHn5i4SGU75QRvDvyk2i4H+RgV3ccK5c4HjYfts2swmM2ushGXPePZ0W/JQ4QJCui8jG9PrJmrIEQ5xU1OQs0infiI8vo1Spxsj2HqjgLjAWF9yH5NiHYNG89EHB+BFA2G+djnew+eZBEqqzIm+lc=
  - secure: IpA69dN/uc3MBw0F2u+J4tH37uHuhhnTiKC6SdLSky5NgtCtWkbJliECR6J/2tyQ29ZIPUxuBZwLoabik/Ym3/FHJ8uGGTs0nXBeuKp/aToalOZ/fBPTyxIRWHV4iZTDu3Cq/jXu1lZELmHloGMWjD9sVAwHxi8TJJHdkqzyDMhUQDI38bIKY7zaABEOL23sK0i0GULcMXil5QURejEzN7RPWfaXxCLRSYaJu6AygBVFjvpDALCRu/WfyXfyiIyII2QZtI7+kqTsuIsZbGKhX/BFGNipcrqaU+YyDpEn0GUpVmwE96RP8hsiGbafAFvaRo+GRstVQROkdIpOYX8YvjuEu182Aor+2rDQ4cjDw2IdCP+dnLcd0eduEwVMUATXyMmjU1wy4rsYv4QBgrwK8qW3/DMtoZDUvvIKQfHLiCzjEcYVyU46fzKDhVU87qeeZ+9fPXd21xsXmXJdeIDJDC43RzP8zFXzsSdLPK870TdUob5H8P4PVHn469u1FmLzlWFZyBW7wQwm8OmTLbhdUXtPNIHAMkkGMrzNgGOMRJ/Szqf2V0EsO3xqlZVT22UZF4Q29sow5TXSwjn/nwyBfqz1Qo/8t/MfAZrMPYHwI3YUn5Dtt3aWKPc3hZ8w2teYS2kg0hcHzzMdTB1H+rIRrT9ZR+S/U3OTeaxPJKignz8=
